# Configuración de Hyprlock - Estética Tokyonight

background {
    monitor =
    # Color de fondo azulado oscuro idéntico a tu terminal
    color = rgb(1a1b26)
    
    # Si en el futuro quieres que use tu fondo de pantalla difuminado,
    # descomenta las líneas de abajo quitando el '#' y pon la ruta de tu imagen:
    # path = /home/javi/Imágenes/tu_fondo.png
    # blur_passes = 2
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.4
    dots_fade_time = 100
    
    # Colores de los bordes a juego con el prompt (azul y verde)
    outer_color = rgb(7aa2f7)
    inner_color = rgb(24283b)
    font_color = rgb(c0caf5)
    fade_on_empty = false
    
    # Texto que sale en la caja
    placeholder_text = <span foreground="##7aa2f7">Introduce contraseña...</span>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

# Reloj en pantalla
label {
    monitor =
    text = $TIME
    color = rgb(c0caf5)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# Mensaje de bienvenida minimalista
label {
    monitor =
    text = Hola, $USER 󰣇
    color = rgb(7aa2f7)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 10
    halign = center
    valign = center
}
